### PR TITLE
For external ceph cluster also admin keyring file path should be provided

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by rhafer** [comment]
This needs to be merged before https://github.com/crowbar/barclamp-cinder/pull/243

**Comment by rhafer** [comment]
@mjura Is there a special reason why you didn't include this in https://github.com/crowbar/barclamp-cinder/pull/243?

**Comment by tboerger** [comment]
LGTM

**Comment by rhafer** [comment]
+1

**Pull request merged**
