### PR TITLE
Allow deploying cinder-volume on SLE12 nodes

### PR DESCRIPTION
**Pull request by mjura**
This is initial PR which allow to deploy cinder-volume role on SLE12 nodes. 

It was only tested with RADOS backend!

### CODE REVIEW

**Comment by vuntz** [comment]
Can we test at least the two lvm backends also before merging this? (including rebooting the cinder volume node)

**Comment by mjura** [comment]
It was tested also with RAW backend and works fine.

It is failing still during using `local` backend!

**Comment by dirkmueller** [comment]
There is https://trello.com/c/QcOIZeiS/834-5-sle12-make-cinder-roles-deployable-on-sle12 for fixing cinder-volume and sle12

**Comment by mjura** [comment]
@vuntz, @dirkmueller: Should we drop support for SLE11SP3?

**Comment by mjura** [comment]
It was tested with `local`, `raw` and `rados` backend, after node reboot everything works fine.

**Comment by vuntz** [comment]
> @vuntz, @dirkmueller: Should we drop support for SLE11SP3?

Not yet, unless it's creating big issues.

**Comment by nkrinner** [comment]
+1

**Comment by rsalevsky** [comment]
:+1: 

Tested different variants of deploying it with SLE12 and SLE11SP3 (Controller and Volumes).

**Pull request merged**
