### PR TITLE
Finish proper integration of ceph recipe

### PR DESCRIPTION
**Pull request by vuntz**
This supersedes https://github.com/crowbar/barclamp-cinder/pull/246

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by rhafer** [comment]
In general this looks good to me. And while I somewhat agree with https://github.com/vuntz/barclamp-cinder/commit/471daa77a890164713bf6b82539ea5d096e25d5e I wonder if/how/where we should handle the case when the user specifies multiple ceph backends in cinder that use different ceph clusters but the same usernames. Should we at least warn about that case during the proposal validation?

**Comment by vuntz** [comment]
> And while I somewhat agree with https://github.com/vuntz/barclamp-cinder/commit/471daa77a890164713bf6b82539ea5d096e25d5e I wonder if/how/where we should handle the case when the user specifies multiple ceph backends in cinder that use different ceph clusters but the same usernames. Should we at least warn about that case during the proposal validation?

We should definitely deal with it somehow, and I think for now, validation is likely the best option. But I'd do it in a later PR, tbh (or, well, I'd let @mjura do it ;-)). This PR is really to fix the regression that was introduced by the recent changes (single loop that breaks multi-cluster setup).

Also, I made sure to have a commit that reverts the use of md5 hashes so we could easily revert that if we decide it's the way to go.

**Comment by rhafer** [comment]
> We should definitely deal with it somehow, and I think for now, validation is likely the best option. But I'd do it in a later PR, tbh (or, well, I'd let @mjura do it ;-)). This PR is really to fix the regression that was introduced by the recent changes (single loop that breaks multi-cluster setup).

Ok. That sounds like a plan. I'll add a new card for that. 

+1 for this PR.

**Pull request merged**
