### PR TITLE
Fix the totally weird way tgtd was handled

### PR DESCRIPTION
**Pull request by vuntz**
This all came from the fact that tgtd wasn't running on a controller, because it was stopped and chef never restarts it.

### CODE REVIEW

**Comment by dirkmueller** [comment]
I'm not sure thats a good idea..  our init script does do weird stuff on a restart.

**Comment by vuntz** [comment]
@dirkmueller: afaik, there should be no real change compared to what we are doing today. Except that the code should be less confusing.

Or am I missing something?

**Comment by tboerger** [comment]
:+1:

**Comment by dirkmueller** [comment]
@vuntz from my perspective you're inverting the platform check condition from unless to if.. I don't think thats a good idea.

**Comment by vuntz** [comment]
@dirkmueller good catch. Fixed (but still untested)

**Comment by dirkmueller** [comment]
+1

**Comment by mjura** [comment]
@vuntz I think that this can be merged

:+1:

**Comment by rsalevsky** [comment]
@vuntz Is this PR ready to merge? The title is a little bit unclear due to the WIP.

**Comment by vuntz** [comment]
@rsalevsky sorry, I never actually tested it, hence the title. I can test it in my next deployment, though.

**Comment by vuntz** [comment]
Seems to work fine, so let's try it in master.

**Pull request merged**
